cargo-features = ["strip"]

[package]
name = "compiler2"
version = "0.1.0"
edition = "2021"

[dependencies]
jemallocator = "0.3.2"

[profile.release]
strip = true
lto = true
panic = "abort"
# debug = true